apiVersion: apps/v1
kind: Deployment
metadata:
  name: habit-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: habit-mongo
  template:
    metadata:
      labels:
        app: habit-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: habit-mongo
spec:
  type: ClusterIP
  selector:
    app: habit-mongo
  ports:
    - port: 27017
      targetPort: 27017 