apiVersion: apps/v1
kind: Deployment
metadata:
  name: habit-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: habit-backend
  template:
    metadata:
      labels:
        app: habit-backend
    spec:
      containers:
        - name: backend
          image: habit-backend:latest
          env:
            - name: MONGO_URI
              value: mongodb://habit-mongo:27017/habitdb
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: habit-backend
spec:
  type: NodePort
  selector:
    app: habit-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500 