apiVersion: apps/v1
kind: Deployment
metadata:
  name: habit-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: habit-frontend
  template:
    metadata:
      labels:
        app: habit-frontend
    spec:
      containers:
        - name: frontend
          image: habit-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: habit-frontend
spec:
  type: NodePort
  selector:
    app: habit-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 